#
# wxWidgets configuration - MinGW64
#
SET(WXWIDGETS_VER_COMPACT @WX_VER_COMPACT@)
SET(WXWIDGETS_DLL_SUFFIX "gcc1210_x64.dll")

#libraries
SET(WX_adv ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_adv.a)
SET(WX_advd ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_adv.a)
SET(WX_aui ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_aui.a)
SET(WX_auid ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_aui.a)
SET(WX_base ${wxWidgets_LIB_DIR}/libwxbase32u.a)
SET(WX_based ${wxWidgets_LIB_DIR}/libwxbase32ud.a)
SET(WX_core ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_core.a)
SET(WX_cored ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_core.a)
SET(WX_expat ${wxWidgets_LIB_DIR}/libwxexpat.a)
SET(WX_expatd ${wxWidgets_LIB_DIR}/libwxexpatd.a)
SET(WX_gl ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_gl.a)
SET(WX_gld ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_gl.a)
SET(WX_html ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_html.a)
SET(WX_htmld ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_html.a)
SET(WX_jpeg ${wxWidgets_LIB_DIR}/libwxjpeg.a)
SET(WX_jpegd ${wxWidgets_LIB_DIR}/libwxjpegd.a)
SET(WX_media ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_media.a)
SET(WX_mediad ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_media.a)
SET(WX_net ${wxWidgets_LIB_DIR}/libwxbase32u_net.a)
SET(WX_netd ${wxWidgets_LIB_DIR}/libwxbase32ud_net.a)
SET(WX_png ${wxWidgets_LIB_DIR}/libwxpng.a)
SET(WX_pngd ${wxWidgets_LIB_DIR}/libwxpngd.a)
SET(WX_propgrid ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_propgrid.a)
SET(WX_propgridd ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_propgrid.a)
SET(WX_qa ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_qa.a)
SET(WX_qad ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_qa.a)
SET(WX_regex ${wxWidgets_LIB_DIR}/libwxregexu.a)
SET(WX_regexd ${wxWidgets_LIB_DIR}/libwxregexud.a)
SET(WX_ribbon ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_ribbon.a)
SET(WX_ribbond ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_ribbon.a)
SET(WX_richtext ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_richtext.a)
SET(WX_richtextd ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_richtext.a)
SET(WX_scintilla ${wxWidgets_LIB_DIR}/libwxscintilla.a)
SET(WX_scintillad ${wxWidgets_LIB_DIR}/libwxscintillad.a)
SET(WX_stc ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_stc.a)
SET(WX_stcd ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_stc.a)
SET(WX_tiff ${wxWidgets_LIB_DIR}/libwxtiff.a)
SET(WX_tiffd ${wxWidgets_LIB_DIR}/libwxtiffd.a)
SET(WX_webview ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_webview.a)
SET(WX_webviewd ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_webview.a)
SET(WX_xml ${wxWidgets_LIB_DIR}/libwxbase32u_xml.a)
SET(WX_xmld ${wxWidgets_LIB_DIR}/libwxbase32ud_xml.a)
SET(WX_xrc ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}u_xrc.a)
SET(WX_xrcd ${wxWidgets_LIB_DIR}/libwxmsw${WXWIDGETS_VER_COMPACT}ud_xrc.a)
SET(WX_zlib ${wxWidgets_LIB_DIR}/libwxzlib.a)
SET(WX_zlibd ${wxWidgets_LIB_DIR}/libwxzlibd.a)

SET(wxWidgets_USE_REL_AND_DBG OFF)