#
# wxWidgets configuration - MSVC
#
SET(WXWIDGETS_VER_COMPACT @WX_VER_COMPACT@)
SET(WXWIDGETS_DLL_SUFFIX "vc14x_x64.dll")

#libraries
SET(WX_adv ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_adv.lib)
SET(WX_advd ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_adv.lib)
SET(WX_aui ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_aui.lib)
SET(WX_auid ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_aui.lib)
SET(WX_base ${wxWidgets_LIB_DIR}/wxbase32u.lib)
SET(WX_based ${wxWidgets_LIB_DIR}/wxbase32ud.lib)
SET(WX_core ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_core.lib)
SET(WX_cored ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_core.lib)
SET(WX_expat ${wxWidgets_LIB_DIR}/wxexpat.lib)
SET(WX_expatd ${wxWidgets_LIB_DIR}/wxexpatd.lib)
SET(WX_gl ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_gl.lib)
SET(WX_gld ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_gl.lib)
SET(WX_html ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_html.lib)
SET(WX_htmld ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_html.lib)
SET(WX_jpeg ${wxWidgets_LIB_DIR}/wxjpeg.lib)
SET(WX_jpegd ${wxWidgets_LIB_DIR}/wxjpegd.lib)
SET(WX_media ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_media.lib)
SET(WX_mediad ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_media.lib)
SET(WX_net ${wxWidgets_LIB_DIR}/wxbase32u_net.lib)
SET(WX_netd ${wxWidgets_LIB_DIR}/wxbase32ud_net.lib)
SET(WX_png ${wxWidgets_LIB_DIR}/wxpng.lib)
SET(WX_pngd ${wxWidgets_LIB_DIR}/wxpngd.lib)
SET(WX_propgrid ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_propgrid.lib)
SET(WX_propgridd ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_propgrid.lib)
SET(WX_qa ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_qa.lib)
SET(WX_qad ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_qa.lib)
SET(WX_regex ${wxWidgets_LIB_DIR}/wxregexu.lib)
SET(WX_regexd ${wxWidgets_LIB_DIR}/wxregexud.lib)
SET(WX_ribbon ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_ribbon.lib)
SET(WX_ribbond ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_ribbon.lib)
SET(WX_richtext ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_richtext.lib)
SET(WX_richtextd ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_richtext.lib)
SET(WX_scintilla ${wxWidgets_LIB_DIR}/wxscintilla.lib)
SET(WX_scintillad ${wxWidgets_LIB_DIR}/wxscintillad.lib)
SET(WX_stc ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_stc.lib)
SET(WX_stcd ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_stc.lib)
SET(WX_tiff ${wxWidgets_LIB_DIR}/wxtiff.lib)
SET(WX_tiffd ${wxWidgets_LIB_DIR}/wxtiffd.lib)
SET(WX_webview ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_webview.lib)
SET(WX_webviewd ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_webview.lib)
SET(WX_xml ${wxWidgets_LIB_DIR}/wxbase32u_xml.lib)
SET(WX_xmld ${wxWidgets_LIB_DIR}/wxbase32ud_xml.lib)
SET(WX_xrc ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}u_xrc.lib)
SET(WX_xrcd ${wxWidgets_LIB_DIR}/wxmsw${WXWIDGETS_VER_COMPACT}ud_xrc.lib)
SET(WX_zlib ${wxWidgets_LIB_DIR}/wxzlib.lib)
SET(WX_zlibd ${wxWidgets_LIB_DIR}/wxzlibd.lib)

SET(wxWidgets_USE_REL_AND_DBG ON)
