#
# wxWidgets configuration - MSVC
#
SET(WXWIDGETS_VER_COMPACT @WX_VER_COMPACT@)
SET(WXWIDGETS_DLL_SUFFIX @WX_MSVC_DLL_SUFFIX@_x64)
INCLUDE(${wxWidgets_ROOT_DIR}/wx-widgets.cmake)
SET(wxWidgets_USE_REL_AND_DBG ON)
